steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/projectcc-api:$COMMIT_SHA", "."]
  
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/projectcc-api:$COMMIT_SHA"]
  
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "projectcc-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/projectcc-api:$COMMIT_SHA"
      - "--region"
      - "asia-southeast2"
      - "--platform"
      - "managed" # Ensure deploying to managed Cloud Run
      - "--allow-unauthenticated" # Add this if you want the service to be publicly accessible

images:
  - "gcr.io/$PROJECT_ID/projectcc-api:$COMMIT_SHA"
